<?php

if ( !defined( 'DMS' ) )
	die( 'Forbidden' );

class DMS_Option_Type_NewIcon extends DMS_Option_Type {

	/**
	 * Prevent enqueue same font style twice, in case it is used in multiple sets
	 * @var array
	 */
	private $enqueued_font_styles = array();

	public function get_type() {
		return 'new-icon';
	}

	/**
	 * @internal
	 */
	public function _get_backend_width_type() {
		return 'full';
	}

	/**
	 * @internal
	 * {@inheritdoc}
	 */
	protected function _enqueue_static( $id, $option, $data ) {

		$uri = KINTER_THEME_URI . '/components/option-types/' . $this->get_type() . '/static';

		wp_enqueue_style(
		'dms-option-' . $this->get_type(), $uri . '/css/backend.css'
		);

		wp_enqueue_script(
		'dms-option-' . $this->get_type(), $uri . '/js/backend.js', array( 'jquery', 'dms-events' ), dms()->manifest->get_version()
		);

		$sets = $this->get_sets();

		if ( isset( $sets[ $option[ 'set' ] ] ) ) {
			$set = $sets[ $option[ 'set' ] ];

			unset( $sets );

			/**
			 * user hash as array key instead of src, because src can be a very long data-url string
			 */
			$style_hash = md5( $set[ 'font-style-src' ] );

			if ( !isset( $this->enqueued_font_styles[ $style_hash ] ) ) {
				wp_enqueue_style(
				"dms-option-type-{$this->get_type()}-font-{$option[ 'set' ]}", $set[ 'font-style-src' ], array(), dms()->manifest->get_version()
				);

				$this->enqueued_font_styles[ $style_hash ] = true;
			}
		}

		return true;
	}

	/**
	 * @internal
	 */
	protected function _render( $id, $option, $data ) {


		$sets = $this->get_sets();

		if ( isset( $sets[ $option[ 'set' ] ] ) ) {
			$set = $sets[ $option[ 'set' ] ];
		} else {
			$set = $this->generate_unknown_set( $data[ 'value' ] );
		}

		unset( $sets );

		$option[ 'attr' ][ 'value' ] = (string) $data[ 'value' ];

		return dms_render_view( KINTER_COMPONENTS . '/option-types/' . $this->get_type() . '/view.php', compact( 'id', 'option', 'data', 'set' ) );
	}

	/**
	 * @internal
	 */
	protected function _get_value_from_input( $option, $input_value ) {
		if ( is_null( $input_value ) ) {
			return $option[ 'value' ];
		}

		$sets = $this->get_sets();

		if ( isset( $sets[ $option[ 'set' ] ] ) ) {
			$set = $sets[ $option[ 'set' ] ];
		} else {
			$set = $this->generate_unknown_set( $input_value );
		}

		unset( $sets );

		if ( !isset( $set[ 'icons' ][ $input_value ] ) ) {
			$input_value = $option[ 'value' ];
		}

		return (string) $input_value;
	}

	/**
	 * @internal
	 */
	protected function _get_defaults() {
		return array(
			'value'	 => '',
			'set'	 => 'font-awesome',
		);
	}

	private function get_sets() {
		$cache_key = 'dms_option_type_icon/sets';

		try {
			return DMS_Cache::get( $cache_key );
		} catch ( DMS_Cache_Not_Found_Exception $e ) {
			$sets = apply_filters( 'dms_option_type_icon_sets', $this->get_default_sets() );

			// do not allow overwrite default sets
			$sets = array_merge( $sets, $this->get_default_sets() );

			DMS_Cache::set( $cache_key, $sets );

			return $sets;
		}
	}

	private function generate_unknown_set( $icon ) {
		return array(
			'font-style-src'	 => 'data:text/css;charset=utf-8;base64,LyoqLw==', // fixme: WP will transform this to `http://domain.com/data:text/css;...`
			'container-class'	 => '',
			'groups'			 => array(
				'unknown' => esc_html__( 'Unknown Set', 'kinter' ),
			),
			'icons'				 => array(
				$icon => array( 'group' => 'unknown' ),
			),
		);
	}

	private function get_default_sets() {
		return array(
			'font-awesome' => array( // http://fortawesome.github.io/Font-Awesome/icons
				'font-style-src'	 => dms_get_framework_directory_uri( '/static/libs/font-awesome/css/font-awesome.min.css' ),
				'container-class'	 => 'fa-lg', // some fonts need special wrapper class to display properly
				'groups'			 => array(
					'brand'				 => esc_html__( 'Brand Icons', 'kinter' ),
					'solid'				 => esc_html__( 'Solid Icons', 'kinter' ),
					'regular'			 => esc_html__( 'Regular Icons', 'kinter' ),
				),
				'icons'				 => array(
					'fab fa-500px' => array( 'group' => 'brand' ),
					'fab fa-accessible-icon' => array( 'group' => 'brand' ),
					'fab fa-accusoft' => array( 'group' => 'brand' ),
					'fab fa-adn' => array( 'group' => 'brand' ),
					'fab fa-adversal' => array( 'group' => 'brand' ),
					'fab fa-affiliatetheme' => array( 'group' => 'brand' ),
					'fab fa-algolia' => array( 'group' => 'brand' ),
					'fab fa-amazon' => array( 'group' => 'brand' ),
					'fab fa-amazon-pay' => array( 'group' => 'brand' ),
					'fab fa-amilia' => array( 'group' => 'brand' ),
					'fab fa-android' => array( 'group' => 'brand' ),
					'fab fa-angellist' => array( 'group' => 'brand' ),
					'fab fa-angrycreative' => array( 'group' => 'brand' ),
					'fab fa-angular' => array( 'group' => 'brand' ),
					'fab fa-app-store' => array( 'group' => 'brand' ),
					'fab fa-app-store-ios' => array( 'group' => 'brand' ),
					'fab fa-apper' => array( 'group' => 'brand' ),
					'fab fa-apple' => array( 'group' => 'brand' ),
					'fab fa-apple-pay' => array( 'group' => 'brand' ),
					'fab fa-asymmetrik' => array( 'group' => 'brand' ),
					'fab fa-audible' => array( 'group' => 'brand' ),
					'fab fa-autoprefixer' => array( 'group' => 'brand' ),
					'fab fa-avianex' => array( 'group' => 'brand' ),
					'fab fa-aviato' => array( 'group' => 'brand' ),
					'fab fa-aws' => array( 'group' => 'brand' ),
					'fab fa-bandcamp' => array( 'group' => 'brand' ),
					'fab fa-behance' => array( 'group' => 'brand' ),
					'fab fa-behance-square' => array( 'group' => 'brand' ),
					'fab fa-bimobject' => array( 'group' => 'brand' ),
					'fab fa-bitbucket' => array( 'group' => 'brand' ),
					'fab fa-bitcoin' => array( 'group' => 'brand' ),
					'fab fa-bity' => array( 'group' => 'brand' ),
					'fab fa-black-tie' => array( 'group' => 'brand' ),
					'fab fa-blackberry' => array( 'group' => 'brand' ),
					'fab fa-blogger' => array( 'group' => 'brand' ),
					'fab fa-blogger-b' => array( 'group' => 'brand' ),
					'fab fa-bluetooth' => array( 'group' => 'brand' ),
					'fab fa-bluetooth-b' => array( 'group' => 'brand' ),
					'fab fa-btc' => array( 'group' => 'brand' ),
					'fab fa-buromobelexperte' => array( 'group' => 'brand' ),
					'fab fa-buysellads' => array( 'group' => 'brand' ),
					'fab fa-cc-amazon-pay' => array( 'group' => 'brand' ),
					'fab fa-cc-amex' => array( 'group' => 'brand' ),
					'fab fa-cc-apple-pay' => array( 'group' => 'brand' ),
					'fab fa-cc-diners-club' => array( 'group' => 'brand' ),
					'fab fa-cc-discover' => array( 'group' => 'brand' ),
					'fab fa-cc-jcb' => array( 'group' => 'brand' ),
					'fab fa-cc-mastercard' => array( 'group' => 'brand' ),
					'fab fa-cc-paypal' => array( 'group' => 'brand' ),
					'fab fa-cc-stripe' => array( 'group' => 'brand' ),
					'fab fa-cc-visa' => array( 'group' => 'brand' ),
					'fab fa-centercode' => array( 'group' => 'brand' ),
					'fab fa-chrome' => array( 'group' => 'brand' ),
					'fab fa-cloudscale' => array( 'group' => 'brand' ),
					'fab fa-cloudsmith' => array( 'group' => 'brand' ),
					'fab fa-cloudversify' => array( 'group' => 'brand' ),
					'fab fa-codepen' => array( 'group' => 'brand' ),
					'fab fa-codiepie' => array( 'group' => 'brand' ),
					'fab fa-connectdevelop' => array( 'group' => 'brand' ),
					'fab fa-contao' => array( 'group' => 'brand' ),
					'fab fa-cpanel' => array( 'group' => 'brand' ),
					'fab fa-creative-commons' => array( 'group' => 'brand' ),
					'fab fa-css3' => array( 'group' => 'brand' ),
					'fab fa-css3-alt' => array( 'group' => 'brand' ),
					'fab fa-cuttlefish' => array( 'group' => 'brand' ),
					'fab fa-d-and-d' => array( 'group' => 'brand' ),
					'fab fa-dashcube' => array( 'group' => 'brand' ),
					'fab fa-delicious' => array( 'group' => 'brand' ),
					'fab fa-deploydog' => array( 'group' => 'brand' ),
					'fab fa-deskpro' => array( 'group' => 'brand' ),
					'fab fa-deviantart' => array( 'group' => 'brand' ),
					'fab fa-digg' => array( 'group' => 'brand' ),
					'fab fa-digital-ocean' => array( 'group' => 'brand' ),
					'fab fa-discord' => array( 'group' => 'brand' ),
					'fab fa-discourse' => array( 'group' => 'brand' ),
					'fab fa-dochub' => array( 'group' => 'brand' ),
					'fab fa-docker' => array( 'group' => 'brand' ),
					'fab fa-draft2digital' => array( 'group' => 'brand' ),
					'fab fa-dribbble' => array( 'group' => 'brand' ),
					'fab fa-dribbble-square' => array( 'group' => 'brand' ),
					'fab fa-dropbox' => array( 'group' => 'brand' ),
					'fab fa-drupal' => array( 'group' => 'brand' ),
					'fab fa-dyalog' => array( 'group' => 'brand' ),
					'fab fa-earlybirds' => array( 'group' => 'brand' ),
					'fab fa-edge' => array( 'group' => 'brand' ),
					'fab fa-elementor' => array( 'group' => 'brand' ),
					'fab fa-ember' => array( 'group' => 'brand' ),
					'fab fa-empire' => array( 'group' => 'brand' ),
					'fab fa-envira' => array( 'group' => 'brand' ),
					'fab fa-erlang' => array( 'group' => 'brand' ),
					'fab fa-ethereum' => array( 'group' => 'brand' ),
					'fab fa-etsy' => array( 'group' => 'brand' ),
					'fab fa-expeditedssl' => array( 'group' => 'brand' ),
					'fab fa-facebook' => array( 'group' => 'brand' ),
					'fab fa-facebook-f' => array( 'group' => 'brand' ),
					'fab fa-facebook-messenger' => array( 'group' => 'brand' ),
					'fab fa-facebook-square' => array( 'group' => 'brand' ),
					'fab fa-firefox' => array( 'group' => 'brand' ),
					'fab fa-first-order' => array( 'group' => 'brand' ),
					'fab fa-firstdraft' => array( 'group' => 'brand' ),
					'fab fa-flickr' => array( 'group' => 'brand' ),
					'fab fa-flipboard' => array( 'group' => 'brand' ),
					'fab fa-fly' => array( 'group' => 'brand' ),
					'fab fa-font-awesome' => array( 'group' => 'brand' ),
					'fab fa-font-awesome-alt' => array( 'group' => 'brand' ),
					'fab fa-font-awesome-flag' => array( 'group' => 'brand' ),
					'fab fa-fonticons' => array( 'group' => 'brand' ),
					'fab fa-fonticons-fi' => array( 'group' => 'brand' ),
					'fab fa-fort-awesome' => array( 'group' => 'brand' ),
					'fab fa-fort-awesome-alt' => array( 'group' => 'brand' ),
					'fab fa-forumbee' => array( 'group' => 'brand' ),
					'fab fa-foursquare' => array( 'group' => 'brand' ),
					'fab fa-free-code-camp' => array( 'group' => 'brand' ),
					'fab fa-freebsd' => array( 'group' => 'brand' ),
					'fab fa-get-pocket' => array( 'group' => 'brand' ),
					'fab fa-gg' => array( 'group' => 'brand' ),
					'fab fa-gg-circle' => array( 'group' => 'brand' ),
					'fab fa-git' => array( 'group' => 'brand' ),
					'fab fa-git-square' => array( 'group' => 'brand' ),
					'fab fa-github' => array( 'group' => 'brand' ),
					'fab fa-github-alt' => array( 'group' => 'brand' ),
					'fab fa-github-square' => array( 'group' => 'brand' ),
					'fab fa-gitkraken' => array( 'group' => 'brand' ),
					'fab fa-gitlab' => array( 'group' => 'brand' ),
					'fab fa-gitter' => array( 'group' => 'brand' ),
					'fab fa-glide' => array( 'group' => 'brand' ),
					'fab fa-glide-g' => array( 'group' => 'brand' ),
					'fab fa-gofore' => array( 'group' => 'brand' ),
					'fab fa-goodreads' => array( 'group' => 'brand' ),
					'fab fa-goodreads-g' => array( 'group' => 'brand' ),
					'fab fa-google' => array( 'group' => 'brand' ),
					'fab fa-google-drive' => array( 'group' => 'brand' ),
					'fab fa-google-play' => array( 'group' => 'brand' ),
					'fab fa-google-plus' => array( 'group' => 'brand' ),
					'fab fa-google-plus-g' => array( 'group' => 'brand' ),
					'fab fa-google-plus-square' => array( 'group' => 'brand' ),
					'fab fa-google-wallet' => array( 'group' => 'brand' ),
					'fab fa-gratipay' => array( 'group' => 'brand' ),
					'fab fa-grav' => array( 'group' => 'brand' ),
					'fab fa-gripfire' => array( 'group' => 'brand' ),
					'fab fa-grunt' => array( 'group' => 'brand' ),
					'fab fa-gulp' => array( 'group' => 'brand' ),
					'fab fa-hacker-news' => array( 'group' => 'brand' ),
					'fab fa-hacker-news-square' => array( 'group' => 'brand' ),
					'fab fa-hips' => array( 'group' => 'brand' ),
					'fab fa-hire-a-helper' => array( 'group' => 'brand' ),
					'fab fa-hooli' => array( 'group' => 'brand' ),
					'fab fa-hotjar' => array( 'group' => 'brand' ),
					'fab fa-houzz' => array( 'group' => 'brand' ),
					'fab fa-html5' => array( 'group' => 'brand' ),
					'fab fa-hubspot' => array( 'group' => 'brand' ),
					'fab fa-imdb' => array( 'group' => 'brand' ),
					'fab fa-instagram' => array( 'group' => 'brand' ),
					'fab fa-internet-explorer' => array( 'group' => 'brand' ),
					'fab fa-ioxhost' => array( 'group' => 'brand' ),
					'fab fa-itunes' => array( 'group' => 'brand' ),
					'fab fa-itunes-note' => array( 'group' => 'brand' ),
					'fab fa-java' => array( 'group' => 'brand' ),
					'fab fa-jenkins' => array( 'group' => 'brand' ),
					'fab fa-joget' => array( 'group' => 'brand' ),
					'fab fa-joomla' => array( 'group' => 'brand' ),
					'fab fa-js' => array( 'group' => 'brand' ),
					'fab fa-js-square' => array( 'group' => 'brand' ),
					'fab fa-jsfiddle' => array( 'group' => 'brand' ),
					'fab fa-keycdn' => array( 'group' => 'brand' ),
					'fab fa-kickstarter' => array( 'group' => 'brand' ),
					'fab fa-kickstarter-k' => array( 'group' => 'brand' ),
					'fab fa-korvue' => array( 'group' => 'brand' ),
					'fab fa-laravel' => array( 'group' => 'brand' ),
					'fab fa-lastfm' => array( 'group' => 'brand' ),
					'fab fa-lastfm-square' => array( 'group' => 'brand' ),
					'fab fa-leanpub' => array( 'group' => 'brand' ),
					'fab fa-less' => array( 'group' => 'brand' ),
					'fab fa-line' => array( 'group' => 'brand' ),
					'fab fa-linkedin' => array( 'group' => 'brand' ),
					'fab fa-linkedin-in' => array( 'group' => 'brand' ),
					'fab fa-linode' => array( 'group' => 'brand' ),
					'fab fa-linux' => array( 'group' => 'brand' ),
					'fab fa-lyft' => array( 'group' => 'brand' ),
					'fab fa-magento' => array( 'group' => 'brand' ),
					'fab fa-maxcdn' => array( 'group' => 'brand' ),
					'fab fa-medapps' => array( 'group' => 'brand' ),
					'fab fa-medium' => array( 'group' => 'brand' ),
					'fab fa-medium-m' => array( 'group' => 'brand' ),
					'fab fa-medrt' => array( 'group' => 'brand' ),
					'fab fa-meetup' => array( 'group' => 'brand' ),
					'fab fa-microsoft' => array( 'group' => 'brand' ),
					'fab fa-mix' => array( 'group' => 'brand' ),
					'fab fa-mixcloud' => array( 'group' => 'brand' ),
					'fab fa-mizuni' => array( 'group' => 'brand' ),
					'fab fa-modx' => array( 'group' => 'brand' ),
					'fab fa-monero' => array( 'group' => 'brand' ),
					'fab fa-napster' => array( 'group' => 'brand' ),
					'fab fa-nintendo-switch' => array( 'group' => 'brand' ),
					'fab fa-node' => array( 'group' => 'brand' ),
					'fab fa-node-js' => array( 'group' => 'brand' ),
					'fab fa-npm' => array( 'group' => 'brand' ),
					'fab fa-ns8' => array( 'group' => 'brand' ),
					'fab fa-nutritionix' => array( 'group' => 'brand' ),
					'fab fa-odnoklassniki' => array( 'group' => 'brand' ),
					'fab fa-odnoklassniki-square' => array( 'group' => 'brand' ),
					'fab fa-opencart' => array( 'group' => 'brand' ),
					'fab fa-openid' => array( 'group' => 'brand' ),
					'fab fa-opera' => array( 'group' => 'brand' ),
					'fab fa-optin-monster' => array( 'group' => 'brand' ),
					'fab fa-osi' => array( 'group' => 'brand' ),
					'fab fa-page4' => array( 'group' => 'brand' ),
					'fab fa-pagelines' => array( 'group' => 'brand' ),
					'fab fa-palfed' => array( 'group' => 'brand' ),
					'fab fa-patreon' => array( 'group' => 'brand' ),
					'fab fa-paypal' => array( 'group' => 'brand' ),
					'fab fa-periscope' => array( 'group' => 'brand' ),
					'fab fa-phabricator' => array( 'group' => 'brand' ),
					'fab fa-phoenix-framework' => array( 'group' => 'brand' ),
					'fab fa-php' => array( 'group' => 'brand' ),
					'fab fa-pied-piper' => array( 'group' => 'brand' ),
					'fab fa-pied-piper-alt' => array( 'group' => 'brand' ),
					'fab fa-pied-piper-hat' => array( 'group' => 'brand' ),
					'fab fa-pied-piper-pp' => array( 'group' => 'brand' ),
					'fab fa-pinterest' => array( 'group' => 'brand' ),
					'fab fa-pinterest-p' => array( 'group' => 'brand' ),
					'fab fa-pinterest-square' => array( 'group' => 'brand' ),
					'fab fa-playstation' => array( 'group' => 'brand' ),
					'fab fa-product-hunt' => array( 'group' => 'brand' ),
					'fab fa-pushed' => array( 'group' => 'brand' ),
					'fab fa-python' => array( 'group' => 'brand' ),
					'fab fa-qq' => array( 'group' => 'brand' ),
					'fab fa-quinscape' => array( 'group' => 'brand' ),
					'fab fa-quora' => array( 'group' => 'brand' ),
					'fab fa-ravelry' => array( 'group' => 'brand' ),
					'fab fa-react' => array( 'group' => 'brand' ),
					'fab fa-readme' => array( 'group' => 'brand' ),
					'fab fa-rebel' => array( 'group' => 'brand' ),
					'fab fa-red-river' => array( 'group' => 'brand' ),
					'fab fa-reddit' => array( 'group' => 'brand' ),
					'fab fa-reddit-alien' => array( 'group' => 'brand' ),
					'fab fa-reddit-square' => array( 'group' => 'brand' ),
					'fab fa-renren' => array( 'group' => 'brand' ),
					'fab fa-replyd' => array( 'group' => 'brand' ),
					'fab fa-resolving' => array( 'group' => 'brand' ),
					'fab fa-rocketchat' => array( 'group' => 'brand' ),
					'fab fa-rockrms' => array( 'group' => 'brand' ),
					'fab fa-safari' => array( 'group' => 'brand' ),
					'fab fa-sass' => array( 'group' => 'brand' ),
					'fab fa-schlix' => array( 'group' => 'brand' ),
					'fab fa-scribd' => array( 'group' => 'brand' ),
					'fab fa-searchengin' => array( 'group' => 'brand' ),
					'fab fa-sellcast' => array( 'group' => 'brand' ),
					'fab fa-sellsy' => array( 'group' => 'brand' ),
					'fab fa-servicestack' => array( 'group' => 'brand' ),
					'fab fa-shirtsinbulk' => array( 'group' => 'brand' ),
					'fab fa-simplybuilt' => array( 'group' => 'brand' ),
					'fab fa-sistrix' => array( 'group' => 'brand' ),
					'fab fa-skyatlas' => array( 'group' => 'brand' ),
					'fab fa-skype' => array( 'group' => 'brand' ),
					'fab fa-slack' => array( 'group' => 'brand' ),
					'fab fa-slack-hash' => array( 'group' => 'brand' ),
					'fab fa-slideshare' => array( 'group' => 'brand' ),
					'fab fa-snapchat' => array( 'group' => 'brand' ),
					'fab fa-snapchat-ghost' => array( 'group' => 'brand' ),
					'fab fa-snapchat-square' => array( 'group' => 'brand' ),
					'fab fa-soundcloud' => array( 'group' => 'brand' ),
					'fab fa-speakap' => array( 'group' => 'brand' ),
					'fab fa-spotify' => array( 'group' => 'brand' ),
					'fab fa-stack-exchange' => array( 'group' => 'brand' ),
					'fab fa-stack-overflow' => array( 'group' => 'brand' ),
					'fab fa-staylinked' => array( 'group' => 'brand' ),
					'fab fa-steam' => array( 'group' => 'brand' ),
					'fab fa-steam-square' => array( 'group' => 'brand' ),
					'fab fa-steam-symbol' => array( 'group' => 'brand' ),
					'fab fa-sticker-mule' => array( 'group' => 'brand' ),
					'fab fa-strava' => array( 'group' => 'brand' ),
					'fab fa-stripe' => array( 'group' => 'brand' ),
					'fab fa-stripe-s' => array( 'group' => 'brand' ),
					'fab fa-studiovinari' => array( 'group' => 'brand' ),
					'fab fa-stumbleupon' => array( 'group' => 'brand' ),
					'fab fa-stumbleupon-circle' => array( 'group' => 'brand' ),
					'fab fa-superpowers' => array( 'group' => 'brand' ),
					'fab fa-supple' => array( 'group' => 'brand' ),
					'fab fa-telegram' => array( 'group' => 'brand' ),
					'fab fa-telegram-plane' => array( 'group' => 'brand' ),
					'fab fa-tencent-weibo' => array( 'group' => 'brand' ),
					'fab fa-themeisle' => array( 'group' => 'brand' ),
					'fab fa-trello' => array( 'group' => 'brand' ),
					'fab fa-tripadvisor' => array( 'group' => 'brand' ),
					'fab fa-tumblr' => array( 'group' => 'brand' ),
					'fab fa-tumblr-square' => array( 'group' => 'brand' ),
					'fab fa-twitch' => array( 'group' => 'brand' ),
					'fab fa-twitter' => array( 'group' => 'brand' ),
					'fab fa-twitter-square' => array( 'group' => 'brand' ),
					'fab fa-typo3' => array( 'group' => 'brand' ),
					'fab fa-uber' => array( 'group' => 'brand' ),
					'fab fa-uikit' => array( 'group' => 'brand' ),
					'fab fa-uniregistry' => array( 'group' => 'brand' ),
					'fab fa-untappd' => array( 'group' => 'brand' ),
					'fab fa-usb' => array( 'group' => 'brand' ),
					'fab fa-ussunnah' => array( 'group' => 'brand' ),
					'fab fa-vaadin' => array( 'group' => 'brand' ),
					'fab fa-viacoin' => array( 'group' => 'brand' ),
					'fab fa-viadeo' => array( 'group' => 'brand' ),
					'fab fa-viadeo-square' => array( 'group' => 'brand' ),
					'fab fa-viber' => array( 'group' => 'brand' ),
					'fab fa-vimeo' => array( 'group' => 'brand' ),
					'fab fa-vimeo-square' => array( 'group' => 'brand' ),
					'fab fa-vimeo-v' => array( 'group' => 'brand' ),
					'fab fa-vine' => array( 'group' => 'brand' ),
					'fab fa-vk' => array( 'group' => 'brand' ),
					'fab fa-vnv' => array( 'group' => 'brand' ),
					'fab fa-vuejs' => array( 'group' => 'brand' ),
					'fab fa-weibo' => array( 'group' => 'brand' ),
					'fab fa-weixin' => array( 'group' => 'brand' ),
					'fab fa-whatsapp' => array( 'group' => 'brand' ),
					'fab fa-whatsapp-square' => array( 'group' => 'brand' ),
					'fab fa-whmcs' => array( 'group' => 'brand' ),
					'fab fa-wikipedia-w' => array( 'group' => 'brand' ),
					'fab fa-windows' => array( 'group' => 'brand' ),
					'fab fa-wordpress' => array( 'group' => 'brand' ),
					'fab fa-wordpress-simple' => array( 'group' => 'brand' ),
					'fab fa-wpbeginner' => array( 'group' => 'brand' ),
					'fab fa-wpexplorer' => array( 'group' => 'brand' ),
					'fab fa-wpforms' => array( 'group' => 'brand' ),
					'fab fa-xbox' => array( 'group' => 'brand' ),
					'fab fa-xing' => array( 'group' => 'brand' ),
					'fab fa-xing-square' => array( 'group' => 'brand' ),
					'fab fa-y-combinator' => array( 'group' => 'brand' ),
					'fab fa-yahoo' => array( 'group' => 'brand' ),
					'fab fa-yandex' => array( 'group' => 'brand' ),
					'fab fa-yandex-international' => array( 'group' => 'brand' ),
					'fab fa-yelp' => array( 'group' => 'brand' ),
					'fab fa-yoast' => array( 'group' => 'brand' ),
					'fab fa-youtube' => array( 'group' => 'brand' ),
					'fas fa-address-book' => array( 'group' => 'solid' ),
					'fas fa-address-card' => array( 'group' => 'solid' ),
					'fas fa-adjust' => array( 'group' => 'solid' ),
					'fas fa-align-center' => array( 'group' => 'solid' ),
					'fas fa-align-justify' => array( 'group' => 'solid' ),
					'fas fa-align-left' => array( 'group' => 'solid' ),
					'fas fa-align-right' => array( 'group' => 'solid' ),
					'fas fa-allergies' => array( 'group' => 'solid' ),
					'fas fa-ambulance' => array( 'group' => 'solid' ),
					'fas fa-american-sign-language-interpreting' => array( 'group' => 'solid' ),
					'fas fa-anchor' => array( 'group' => 'solid' ),
					'fas fa-angle-double-down' => array( 'group' => 'solid' ),
					'fas fa-angle-double-left' => array( 'group' => 'solid' ),
					'fas fa-angle-double-right' => array( 'group' => 'solid' ),
					'fas fa-angle-double-up' => array( 'group' => 'solid' ),
					'fas fa-angle-down' => array( 'group' => 'solid' ),
					'fas fa-angle-left' => array( 'group' => 'solid' ),
					'fas fa-angle-right' => array( 'group' => 'solid' ),
					'fas fa-angle-up' => array( 'group' => 'solid' ),
					'fas fa-archive' => array( 'group' => 'solid' ),
					'fas fa-arrow-alt-circle-down' => array( 'group' => 'solid' ),
					'fas fa-arrow-alt-circle-left' => array( 'group' => 'solid' ),
					'fas fa-arrow-alt-circle-right' => array( 'group' => 'solid' ),
					'fas fa-arrow-alt-circle-up' => array( 'group' => 'solid' ),
					'fas fa-arrow-circle-down' => array( 'group' => 'solid' ),
					'fas fa-arrow-circle-left' => array( 'group' => 'solid' ),
					'fas fa-arrow-circle-right' => array( 'group' => 'solid' ),
					'fas fa-arrow-circle-up' => array( 'group' => 'solid' ),
					'fas fa-arrow-down' => array( 'group' => 'solid' ),
					'fas fa-arrow-left' => array( 'group' => 'solid' ),
					'fas fa-arrow-right' => array( 'group' => 'solid' ),
					'fas fa-arrow-up' => array( 'group' => 'solid' ),
					'fas fa-arrows-alt' => array( 'group' => 'solid' ),
					'fas fa-arrows-alt-h' => array( 'group' => 'solid' ),
					'fas fa-arrows-alt-v' => array( 'group' => 'solid' ),
					'fas fa-assistive-listening-systems' => array( 'group' => 'solid' ),
					'fas fa-asterisk' => array( 'group' => 'solid' ),
					'fas fa-at' => array( 'group' => 'solid' ),
					'fas fa-audio-description' => array( 'group' => 'solid' ),
					'fas fa-backward' => array( 'group' => 'solid' ),
					'fas fa-balance-scale' => array( 'group' => 'solid' ),
					'fas fa-ban' => array( 'group' => 'solid' ),
					'fas fa-band-aid' => array( 'group' => 'solid' ),
					'fas fa-barcode' => array( 'group' => 'solid' ),
					'fas fa-bars' => array( 'group' => 'solid' ),
					'fas fa-baseball-ball' => array( 'group' => 'solid' ),
					'fas fa-basketball-ball' => array( 'group' => 'solid' ),
					'fas fa-bath' => array( 'group' => 'solid' ),
					'fas fa-battery-empty' => array( 'group' => 'solid' ),
					'fas fa-battery-full' => array( 'group' => 'solid' ),
					'fas fa-battery-half' => array( 'group' => 'solid' ),
					'fas fa-battery-quarter' => array( 'group' => 'solid' ),
					'fas fa-battery-three-quarters' => array( 'group' => 'solid' ),
					'fas fa-bed' => array( 'group' => 'solid' ),
					'fas fa-beer' => array( 'group' => 'solid' ),
					'fas fa-bell' => array( 'group' => 'solid' ),
					'fas fa-bell-slash' => array( 'group' => 'solid' ),
					'fas fa-bicycle' => array( 'group' => 'solid' ),
					'fas fa-binoculars' => array( 'group' => 'solid' ),
					'fas fa-birthday-cake' => array( 'group' => 'solid' ),
					'fas fa-blind' => array( 'group' => 'solid' ),
					'fas fa-bold' => array( 'group' => 'solid' ),
					'fas fa-bolt' => array( 'group' => 'solid' ),
					'fas fa-bomb' => array( 'group' => 'solid' ),
					'fas fa-book' => array( 'group' => 'solid' ),
					'fas fa-bookmark' => array( 'group' => 'solid' ),
					'fas fa-bowling-ball' => array( 'group' => 'solid' ),
					'fas fa-box' => array( 'group' => 'solid' ),
					'fas fa-box-open' => array( 'group' => 'solid' ),
					'fas fa-boxes' => array( 'group' => 'solid' ),
					'fas fa-braille' => array( 'group' => 'solid' ),
					'fas fa-briefcase' => array( 'group' => 'solid' ),
					'fas fa-briefcase-medical' => array( 'group' => 'solid' ),
					'fas fa-bug' => array( 'group' => 'solid' ),
					'fas fa-building' => array( 'group' => 'solid' ),
					'fas fa-bullhorn' => array( 'group' => 'solid' ),
					'fas fa-bullseye' => array( 'group' => 'solid' ),
					'fas fa-burn' => array( 'group' => 'solid' ),
					'fas fa-bus' => array( 'group' => 'solid' ),
					'fas fa-calculator' => array( 'group' => 'solid' ),
					'fas fa-calendar' => array( 'group' => 'solid' ),
					'fas fa-calendar-alt' => array( 'group' => 'solid' ),
					'fas fa-calendar-check' => array( 'group' => 'solid' ),
					'fas fa-calendar-minus' => array( 'group' => 'solid' ),
					'fas fa-calendar-plus' => array( 'group' => 'solid' ),
					'fas fa-calendar-times' => array( 'group' => 'solid' ),
					'fas fa-camera' => array( 'group' => 'solid' ),
					'fas fa-camera-retro' => array( 'group' => 'solid' ),
					'fas fa-capsules' => array( 'group' => 'solid' ),
					'fas fa-car' => array( 'group' => 'solid' ),
					'fas fa-caret-down' => array( 'group' => 'solid' ),
					'fas fa-caret-left' => array( 'group' => 'solid' ),
					'fas fa-caret-right' => array( 'group' => 'solid' ),
					'fas fa-caret-square-down' => array( 'group' => 'solid' ),
					'fas fa-caret-square-left' => array( 'group' => 'solid' ),
					'fas fa-caret-square-right' => array( 'group' => 'solid' ),
					'fas fa-caret-square-up' => array( 'group' => 'solid' ),
					'fas fa-caret-up' => array( 'group' => 'solid' ),
					'fas fa-cart-arrow-down' => array( 'group' => 'solid' ),
					'fas fa-cart-plus' => array( 'group' => 'solid' ),
					'fas fa-certificate' => array( 'group' => 'solid' ),
					'fas fa-chart-area' => array( 'group' => 'solid' ),
					'fas fa-chart-bar' => array( 'group' => 'solid' ),
					'fas fa-chart-line' => array( 'group' => 'solid' ),
					'fas fa-chart-pie' => array( 'group' => 'solid' ),
					'fas fa-check' => array( 'group' => 'solid' ),
					'fas fa-check-circle' => array( 'group' => 'solid' ),
					'fas fa-check-square' => array( 'group' => 'solid' ),
					'fas fa-chess' => array( 'group' => 'solid' ),
					'fas fa-chess-bishop' => array( 'group' => 'solid' ),
					'fas fa-chess-board' => array( 'group' => 'solid' ),
					'fas fa-chess-king' => array( 'group' => 'solid' ),
					'fas fa-chess-knight' => array( 'group' => 'solid' ),
					'fas fa-chess-pawn' => array( 'group' => 'solid' ),
					'fas fa-chess-queen' => array( 'group' => 'solid' ),
					'fas fa-chess-rook' => array( 'group' => 'solid' ),
					'fas fa-chevron-circle-down' => array( 'group' => 'solid' ),
					'fas fa-chevron-circle-left' => array( 'group' => 'solid' ),
					'fas fa-chevron-circle-right' => array( 'group' => 'solid' ),
					'fas fa-chevron-circle-up' => array( 'group' => 'solid' ),
					'fas fa-chevron-down' => array( 'group' => 'solid' ),
					'fas fa-chevron-left' => array( 'group' => 'solid' ),
					'fas fa-chevron-right' => array( 'group' => 'solid' ),
					'fas fa-chevron-up' => array( 'group' => 'solid' ),
					'fas fa-child' => array( 'group' => 'solid' ),
					'fas fa-circle' => array( 'group' => 'solid' ),
					'fas fa-circle-notch' => array( 'group' => 'solid' ),
					'fas fa-clipboard' => array( 'group' => 'solid' ),
					'fas fa-clipboard-check' => array( 'group' => 'solid' ),
					'fas fa-clipboard-list' => array( 'group' => 'solid' ),
					'fas fa-clock' => array( 'group' => 'solid' ),
					'fas fa-clone' => array( 'group' => 'solid' ),
					'fas fa-closed-captioning' => array( 'group' => 'solid' ),
					'fas fa-cloud' => array( 'group' => 'solid' ),
					'fas fa-cloud-download-alt' => array( 'group' => 'solid' ),
					'fas fa-cloud-upload-alt' => array( 'group' => 'solid' ),
					'fas fa-code' => array( 'group' => 'solid' ),
					'fas fa-code-branch' => array( 'group' => 'solid' ),
					'fas fa-coffee' => array( 'group' => 'solid' ),
					'fas fa-cog' => array( 'group' => 'solid' ),
					'fas fa-cogs' => array( 'group' => 'solid' ),
					'fas fa-columns' => array( 'group' => 'solid' ),
					'fas fa-comment' => array( 'group' => 'solid' ),
					'fas fa-comment-alt' => array( 'group' => 'solid' ),
					'fas fa-comment-dots' => array( 'group' => 'solid' ),
					'fas fa-comment-slash' => array( 'group' => 'solid' ),
					'fas fa-comments' => array( 'group' => 'solid' ),
					'fas fa-compass' => array( 'group' => 'solid' ),
					'fas fa-compress' => array( 'group' => 'solid' ),
					'fas fa-copy' => array( 'group' => 'solid' ),
					'fas fa-copyright' => array( 'group' => 'solid' ),
					'fas fa-couch' => array( 'group' => 'solid' ),
					'fas fa-credit-card' => array( 'group' => 'solid' ),
					'fas fa-crop' => array( 'group' => 'solid' ),
					'fas fa-crosshairs' => array( 'group' => 'solid' ),
					'fas fa-cube' => array( 'group' => 'solid' ),
					'fas fa-cubes' => array( 'group' => 'solid' ),
					'fas fa-cut' => array( 'group' => 'solid' ),
					'fas fa-database' => array( 'group' => 'solid' ),
					'fas fa-deaf' => array( 'group' => 'solid' ),
					'fas fa-desktop' => array( 'group' => 'solid' ),
					'fas fa-diagnoses' => array( 'group' => 'solid' ),
					'fas fa-dna' => array( 'group' => 'solid' ),
					'fas fa-dollar-sign' => array( 'group' => 'solid' ),
					'fas fa-dolly' => array( 'group' => 'solid' ),
					'fas fa-dolly-flatbed' => array( 'group' => 'solid' ),
					'fas fa-donate' => array( 'group' => 'solid' ),
					'fas fa-dot-circle' => array( 'group' => 'solid' ),
					'fas fa-dove' => array( 'group' => 'solid' ),
					'fas fa-download' => array( 'group' => 'solid' ),
					'fas fa-edit' => array( 'group' => 'solid' ),
					'fas fa-eject' => array( 'group' => 'solid' ),
					'fas fa-ellipsis-h' => array( 'group' => 'solid' ),
					'fas fa-ellipsis-v' => array( 'group' => 'solid' ),
					'fas fa-envelope' => array( 'group' => 'solid' ),
					'fas fa-envelope-open' => array( 'group' => 'solid' ),
					'fas fa-envelope-square' => array( 'group' => 'solid' ),
					'fas fa-eraser' => array( 'group' => 'solid' ),
					'fas fa-euro-sign' => array( 'group' => 'solid' ),
					'fas fa-exchange-alt' => array( 'group' => 'solid' ),
					'fas fa-exclamation' => array( 'group' => 'solid' ),
					'fas fa-exclamation-circle' => array( 'group' => 'solid' ),
					'fas fa-exclamation-triangle' => array( 'group' => 'solid' ),
					'fas fa-expand' => array( 'group' => 'solid' ),
					'fas fa-expand-arrows-alt' => array( 'group' => 'solid' ),
					'fas fa-external-link-alt' => array( 'group' => 'solid' ),
					'fas fa-external-link-square-alt' => array( 'group' => 'solid' ),
					'fas fa-eye' => array( 'group' => 'solid' ),
					'fas fa-eye-dropper' => array( 'group' => 'solid' ),
					'fas fa-eye-slash' => array( 'group' => 'solid' ),
					'fas fa-fast-backward' => array( 'group' => 'solid' ),
					'fas fa-fast-forward' => array( 'group' => 'solid' ),
					'fas fa-fax' => array( 'group' => 'solid' ),
					'fas fa-female' => array( 'group' => 'solid' ),
					'fas fa-fighter-jet' => array( 'group' => 'solid' ),
					'fas fa-file' => array( 'group' => 'solid' ),
					'fas fa-file-alt' => array( 'group' => 'solid' ),
					'fas fa-file-archive' => array( 'group' => 'solid' ),
					'fas fa-file-audio' => array( 'group' => 'solid' ),
					'fas fa-file-code' => array( 'group' => 'solid' ),
					'fas fa-file-excel' => array( 'group' => 'solid' ),
					'fas fa-file-image' => array( 'group' => 'solid' ),
					'fas fa-file-medical' => array( 'group' => 'solid' ),
					'fas fa-file-medical-alt' => array( 'group' => 'solid' ),
					'fas fa-file-pdf' => array( 'group' => 'solid' ),
					'fas fa-file-powerpoint' => array( 'group' => 'solid' ),
					'fas fa-file-video' => array( 'group' => 'solid' ),
					'fas fa-file-word' => array( 'group' => 'solid' ),
					'fas fa-film' => array( 'group' => 'solid' ),
					'fas fa-filter' => array( 'group' => 'solid' ),
					'fas fa-fire' => array( 'group' => 'solid' ),
					'fas fa-fire-extinguisher' => array( 'group' => 'solid' ),
					'fas fa-first-aid' => array( 'group' => 'solid' ),
					'fas fa-flag' => array( 'group' => 'solid' ),
					'fas fa-flag-checkered' => array( 'group' => 'solid' ),
					'fas fa-flask' => array( 'group' => 'solid' ),
					'fas fa-folder' => array( 'group' => 'solid' ),
					'fas fa-folder-open' => array( 'group' => 'solid' ),
					'fas fa-font' => array( 'group' => 'solid' ),
					'fas fa-football-ball' => array( 'group' => 'solid' ),
					'fas fa-forward' => array( 'group' => 'solid' ),
					'fas fa-frown' => array( 'group' => 'solid' ),
					'fas fa-futbol' => array( 'group' => 'solid' ),
					'fas fa-gamepad' => array( 'group' => 'solid' ),
					'fas fa-gavel' => array( 'group' => 'solid' ),
					'fas fa-gem' => array( 'group' => 'solid' ),
					'fas fa-genderless' => array( 'group' => 'solid' ),
					'fas fa-gift' => array( 'group' => 'solid' ),
					'fas fa-glass-martini' => array( 'group' => 'solid' ),
					'fas fa-globe' => array( 'group' => 'solid' ),
					'fas fa-golf-ball' => array( 'group' => 'solid' ),
					'fas fa-graduation-cap' => array( 'group' => 'solid' ),
					'fas fa-h-square' => array( 'group' => 'solid' ),
					'fas fa-hand-holding' => array( 'group' => 'solid' ),
					'fas fa-hand-holding-heart' => array( 'group' => 'solid' ),
					'fas fa-hand-holding-usd' => array( 'group' => 'solid' ),
					'fas fa-hand-lizard' => array( 'group' => 'solid' ),
					'fas fa-hand-paper' => array( 'group' => 'solid' ),
					'fas fa-hand-peace' => array( 'group' => 'solid' ),
					'fas fa-hand-point-down' => array( 'group' => 'solid' ),
					'fas fa-hand-point-left' => array( 'group' => 'solid' ),
					'fas fa-hand-point-right' => array( 'group' => 'solid' ),
					'fas fa-hand-point-up' => array( 'group' => 'solid' ),
					'fas fa-hand-pointer' => array( 'group' => 'solid' ),
					'fas fa-hand-rock' => array( 'group' => 'solid' ),
					'fas fa-hand-scissors' => array( 'group' => 'solid' ),
					'fas fa-hand-spock' => array( 'group' => 'solid' ),
					'fas fa-hands' => array( 'group' => 'solid' ),
					'fas fa-hands-helping' => array( 'group' => 'solid' ),
					'fas fa-handshake' => array( 'group' => 'solid' ),
					'fas fa-hashtag' => array( 'group' => 'solid' ),
					'fas fa-hdd' => array( 'group' => 'solid' ),
					'fas fa-heading' => array( 'group' => 'solid' ),
					'fas fa-headphones' => array( 'group' => 'solid' ),
					'fas fa-heart' => array( 'group' => 'solid' ),
					'fas fa-heartbeat' => array( 'group' => 'solid' ),
					'fas fa-history' => array( 'group' => 'solid' ),
					'fas fa-hockey-puck' => array( 'group' => 'solid' ),
					'fas fa-home' => array( 'group' => 'solid' ),
					'fas fa-hospital' => array( 'group' => 'solid' ),
					'fas fa-hospital-alt' => array( 'group' => 'solid' ),
					'fas fa-hospital-symbol' => array( 'group' => 'solid' ),
					'fas fa-hourglass' => array( 'group' => 'solid' ),
					'fas fa-hourglass-end' => array( 'group' => 'solid' ),
					'fas fa-hourglass-half' => array( 'group' => 'solid' ),
					'fas fa-hourglass-start' => array( 'group' => 'solid' ),
					'fas fa-i-cursor' => array( 'group' => 'solid' ),
					'fas fa-id-badge' => array( 'group' => 'solid' ),
					'fas fa-id-card' => array( 'group' => 'solid' ),
					'fas fa-id-card-alt' => array( 'group' => 'solid' ),
					'fas fa-image' => array( 'group' => 'solid' ),
					'fas fa-images' => array( 'group' => 'solid' ),
					'fas fa-inbox' => array( 'group' => 'solid' ),
					'fas fa-indent' => array( 'group' => 'solid' ),
					'fas fa-industry' => array( 'group' => 'solid' ),
					'fas fa-info' => array( 'group' => 'solid' ),
					'fas fa-info-circle' => array( 'group' => 'solid' ),
					'fas fa-italic' => array( 'group' => 'solid' ),
					'fas fa-key' => array( 'group' => 'solid' ),
					'fas fa-keyboard' => array( 'group' => 'solid' ),
					'fas fa-language' => array( 'group' => 'solid' ),
					'fas fa-laptop' => array( 'group' => 'solid' ),
					'fas fa-leaf' => array( 'group' => 'solid' ),
					'fas fa-lemon' => array( 'group' => 'solid' ),
					'fas fa-level-down-alt' => array( 'group' => 'solid' ),
					'fas fa-level-up-alt' => array( 'group' => 'solid' ),
					'fas fa-life-ring' => array( 'group' => 'solid' ),
					'fas fa-lightbulb' => array( 'group' => 'solid' ),
					'fas fa-link' => array( 'group' => 'solid' ),
					'fas fa-lira-sign' => array( 'group' => 'solid' ),
					'fas fa-list' => array( 'group' => 'solid' ),
					'fas fa-list-alt' => array( 'group' => 'solid' ),
					'fas fa-list-ol' => array( 'group' => 'solid' ),
					'fas fa-list-ul' => array( 'group' => 'solid' ),
					'fas fa-location-arrow' => array( 'group' => 'solid' ),
					'fas fa-lock' => array( 'group' => 'solid' ),
					'fas fa-lock-open' => array( 'group' => 'solid' ),
					'fas fa-long-arrow-alt-down' => array( 'group' => 'solid' ),
					'fas fa-long-arrow-alt-left' => array( 'group' => 'solid' ),
					'fas fa-long-arrow-alt-right' => array( 'group' => 'solid' ),
					'fas fa-long-arrow-alt-up' => array( 'group' => 'solid' ),
					'fas fa-low-vision' => array( 'group' => 'solid' ),
					'fas fa-magic' => array( 'group' => 'solid' ),
					'fas fa-magnet' => array( 'group' => 'solid' ),
					'fas fa-male' => array( 'group' => 'solid' ),
					'fas fa-map' => array( 'group' => 'solid' ),
					'fas fa-map-marker' => array( 'group' => 'solid' ),
					'fas fa-map-marker-alt' => array( 'group' => 'solid' ),
					'fas fa-map-pin' => array( 'group' => 'solid' ),
					'fas fa-map-signs' => array( 'group' => 'solid' ),
					'fas fa-mars' => array( 'group' => 'solid' ),
					'fas fa-mars-double' => array( 'group' => 'solid' ),
					'fas fa-mars-stroke' => array( 'group' => 'solid' ),
					'fas fa-mars-stroke-h' => array( 'group' => 'solid' ),
					'fas fa-mars-stroke-v' => array( 'group' => 'solid' ),
					'fas fa-medkit' => array( 'group' => 'solid' ),
					'fas fa-meh' => array( 'group' => 'solid' ),
					'fas fa-mercury' => array( 'group' => 'solid' ),
					'fas fa-microchip' => array( 'group' => 'solid' ),
					'fas fa-microphone' => array( 'group' => 'solid' ),
					'fas fa-microphone-slash' => array( 'group' => 'solid' ),
					'fas fa-minus' => array( 'group' => 'solid' ),
					'fas fa-minus-circle' => array( 'group' => 'solid' ),
					'fas fa-minus-square' => array( 'group' => 'solid' ),
					'fas fa-mobile' => array( 'group' => 'solid' ),
					'fas fa-mobile-alt' => array( 'group' => 'solid' ),
					'fas fa-money-bill-alt' => array( 'group' => 'solid' ),
					'fas fa-moon' => array( 'group' => 'solid' ),
					'fas fa-motorcycle' => array( 'group' => 'solid' ),
					'fas fa-mouse-pointer' => array( 'group' => 'solid' ),
					'fas fa-music' => array( 'group' => 'solid' ),
					'fas fa-neuter' => array( 'group' => 'solid' ),
					'fas fa-newspaper' => array( 'group' => 'solid' ),
					'fas fa-notes-medical' => array( 'group' => 'solid' ),
					'fas fa-object-group' => array( 'group' => 'solid' ),
					'fas fa-object-ungroup' => array( 'group' => 'solid' ),
					'fas fa-outdent' => array( 'group' => 'solid' ),
					'fas fa-paint-brush' => array( 'group' => 'solid' ),
					'fas fa-pallet' => array( 'group' => 'solid' ),
					'fas fa-paper-plane' => array( 'group' => 'solid' ),
					'fas fa-paperclip' => array( 'group' => 'solid' ),
					'fas fa-parachute-box' => array( 'group' => 'solid' ),
					'fas fa-paragraph' => array( 'group' => 'solid' ),
					'fas fa-paste' => array( 'group' => 'solid' ),
					'fas fa-pause' => array( 'group' => 'solid' ),
					'fas fa-pause-circle' => array( 'group' => 'solid' ),
					'fas fa-paw' => array( 'group' => 'solid' ),
					'fas fa-pen-square' => array( 'group' => 'solid' ),
					'fas fa-pencil-alt' => array( 'group' => 'solid' ),
					'fas fa-people-carry' => array( 'group' => 'solid' ),
					'fas fa-percent' => array( 'group' => 'solid' ),
					'fas fa-phone' => array( 'group' => 'solid' ),
					'fas fa-phone-slash' => array( 'group' => 'solid' ),
					'fas fa-phone-square' => array( 'group' => 'solid' ),
					'fas fa-phone-volume' => array( 'group' => 'solid' ),
					'fas fa-piggy-bank' => array( 'group' => 'solid' ),
					'fas fa-pills' => array( 'group' => 'solid' ),
					'fas fa-plane' => array( 'group' => 'solid' ),
					'fas fa-play' => array( 'group' => 'solid' ),
					'fas fa-play-circle' => array( 'group' => 'solid' ),
					'fas fa-plug' => array( 'group' => 'solid' ),
					'fas fa-plus' => array( 'group' => 'solid' ),
					'fas fa-plus-circle' => array( 'group' => 'solid' ),
					'fas fa-plus-square' => array( 'group' => 'solid' ),
					'fas fa-podcast' => array( 'group' => 'solid' ),
					'fas fa-poo' => array( 'group' => 'solid' ),
					'fas fa-pound-sign' => array( 'group' => 'solid' ),
					'fas fa-power-off' => array( 'group' => 'solid' ),
					'fas fa-prescription-bottle' => array( 'group' => 'solid' ),
					'fas fa-prescription-bottle-alt' => array( 'group' => 'solid' ),
					'fas fa-print' => array( 'group' => 'solid' ),
					'fas fa-procedures' => array( 'group' => 'solid' ),
					'fas fa-puzzle-piece' => array( 'group' => 'solid' ),
					'fas fa-qrcode' => array( 'group' => 'solid' ),
					'fas fa-question' => array( 'group' => 'solid' ),
					'fas fa-question-circle' => array( 'group' => 'solid' ),
					'fas fa-quidditch' => array( 'group' => 'solid' ),
					'fas fa-quote-left' => array( 'group' => 'solid' ),
					'fas fa-quote-right' => array( 'group' => 'solid' ),
					'fas fa-random' => array( 'group' => 'solid' ),
					'fas fa-recycle' => array( 'group' => 'solid' ),
					'fas fa-redo' => array( 'group' => 'solid' ),
					'fas fa-redo-alt' => array( 'group' => 'solid' ),
					'fas fa-registered' => array( 'group' => 'solid' ),
					'fas fa-reply-all' => array( 'group' => 'solid' ),
					'fas fa-retweet' => array( 'group' => 'solid' ),
					'fas fa-ribbon' => array( 'group' => 'solid' ),
					'fas fa-road' => array( 'group' => 'solid' ),
					'fas fa-rocket' => array( 'group' => 'solid' ),
					'fas fa-rss' => array( 'group' => 'solid' ),
					'fas fa-rss-square' => array( 'group' => 'solid' ),
					'fas fa-ruble-sign' => array( 'group' => 'solid' ),
					'fas fa-rupee-sign' => array( 'group' => 'solid' ),
					'fas fa-save' => array( 'group' => 'solid' ),
					'fas fa-search' => array( 'group' => 'solid' ),
					'fas fa-search-minus' => array( 'group' => 'solid' ),
					'fas fa-search-plus' => array( 'group' => 'solid' ),
					'fas fa-seedling' => array( 'group' => 'solid' ),
					'fas fa-server' => array( 'group' => 'solid' ),
					'fas fa-share' => array( 'group' => 'solid' ),
					'fas fa-share-alt' => array( 'group' => 'solid' ),
					'fas fa-share-alt-square' => array( 'group' => 'solid' ),
					'fas fa-share-square' => array( 'group' => 'solid' ),
					'fas fa-shekel-sign' => array( 'group' => 'solid' ),
					'fas fa-shield-alt' => array( 'group' => 'solid' ),
					'fas fa-ship' => array( 'group' => 'solid' ),
					'fas fa-shipping-fast' => array( 'group' => 'solid' ),
					'fas fa-shopping-bag' => array( 'group' => 'solid' ),
					'fas fa-shopping-basket' => array( 'group' => 'solid' ),
					'fas fa-shopping-cart' => array( 'group' => 'solid' ),
					'fas fa-shower' => array( 'group' => 'solid' ),
					'fas fa-sign' => array( 'group' => 'solid' ),
					'fas fa-sign-in-alt' => array( 'group' => 'solid' ),
					'fas fa-sign-language' => array( 'group' => 'solid' ),
					'fas fa-sign-out-alt' => array( 'group' => 'solid' ),
					'fas fa-signal' => array( 'group' => 'solid' ),
					'fas fa-sitemap' => array( 'group' => 'solid' ),
					'fas fa-sliders-h' => array( 'group' => 'solid' ),
					'fas fa-smile' => array( 'group' => 'solid' ),
					'fas fa-smoking' => array( 'group' => 'solid' ),
					'fas fa-snowflake' => array( 'group' => 'solid' ),
					'fas fa-sort' => array( 'group' => 'solid' ),
					'fas fa-sort-alpha-down' => array( 'group' => 'solid' ),
					'fas fa-sort-alpha-up' => array( 'group' => 'solid' ),
					'fas fa-sort-amount-down' => array( 'group' => 'solid' ),
					'fas fa-sort-amount-up' => array( 'group' => 'solid' ),
					'fas fa-sort-down' => array( 'group' => 'solid' ),
					'fas fa-sort-numeric-down' => array( 'group' => 'solid' ),
					'fas fa-sort-numeric-up' => array( 'group' => 'solid' ),
					'fas fa-sort-up' => array( 'group' => 'solid' ),
					'fas fa-space-shuttle' => array( 'group' => 'solid' ),
					'fas fa-spinner' => array( 'group' => 'solid' ),
					'fas fa-square' => array( 'group' => 'solid' ),
					'fas fa-square-full' => array( 'group' => 'solid' ),
					'fas fa-star' => array( 'group' => 'solid' ),
					'fas fa-star-half' => array( 'group' => 'solid' ),
					'fas fa-step-backward' => array( 'group' => 'solid' ),
					'fas fa-step-forward' => array( 'group' => 'solid' ),
					'fas fa-stethoscope' => array( 'group' => 'solid' ),
					'fas fa-sticky-note' => array( 'group' => 'solid' ),
					'fas fa-stop' => array( 'group' => 'solid' ),
					'fas fa-stop-circle' => array( 'group' => 'solid' ),
					'fas fa-stopwatch' => array( 'group' => 'solid' ),
					'fas fa-street-view' => array( 'group' => 'solid' ),
					'fas fa-strikethrough' => array( 'group' => 'solid' ),
					'fas fa-subscript' => array( 'group' => 'solid' ),
					'fas fa-subway' => array( 'group' => 'solid' ),
					'fas fa-suitcase' => array( 'group' => 'solid' ),
					'fas fa-sun' => array( 'group' => 'solid' ),
					'fas fa-superscript' => array( 'group' => 'solid' ),
					'fas fa-sync' => array( 'group' => 'solid' ),
					'fas fa-sync-alt' => array( 'group' => 'solid' ),
					'fas fa-syringe' => array( 'group' => 'solid' ),
					'fas fa-table' => array( 'group' => 'solid' ),
					'fas fa-table-tennis' => array( 'group' => 'solid' ),
					'fas fa-tablet' => array( 'group' => 'solid' ),
					'fas fa-tablet-alt' => array( 'group' => 'solid' ),
					'fas fa-tablets' => array( 'group' => 'solid' ),
					'fas fa-tachometer-alt' => array( 'group' => 'solid' ),
					'fas fa-tag' => array( 'group' => 'solid' ),
					'fas fa-tags' => array( 'group' => 'solid' ),
					'fas fa-tape' => array( 'group' => 'solid' ),
					'fas fa-tasks' => array( 'group' => 'solid' ),
					'fas fa-taxi' => array( 'group' => 'solid' ),
					'fas fa-terminal' => array( 'group' => 'solid' ),
					'fas fa-text-height' => array( 'group' => 'solid' ),
					'fas fa-text-width' => array( 'group' => 'solid' ),
					'fas fa-th' => array( 'group' => 'solid' ),
					'fas fa-th-large' => array( 'group' => 'solid' ),
					'fas fa-th-list' => array( 'group' => 'solid' ),
					'fas fa-thermometer' => array( 'group' => 'solid' ),
					'fas fa-thermometer-empty' => array( 'group' => 'solid' ),
					'fas fa-thermometer-full' => array( 'group' => 'solid' ),
					'fas fa-thermometer-half' => array( 'group' => 'solid' ),
					'fas fa-thermometer-quarter' => array( 'group' => 'solid' ),
					'fas fa-thermometer-three-quarters' => array( 'group' => 'solid' ),
					'fas fa-thumbs-down' => array( 'group' => 'solid' ),
					'fas fa-thumbs-up' => array( 'group' => 'solid' ),
					'fas fa-thumbtack' => array( 'group' => 'solid' ),
					'fas fa-ticket-alt' => array( 'group' => 'solid' ),
					'fas fa-times' => array( 'group' => 'solid' ),
					'fas fa-times-circle' => array( 'group' => 'solid' ),
					'fas fa-tint' => array( 'group' => 'solid' ),
					'fas fa-toggle-off' => array( 'group' => 'solid' ),
					'fas fa-toggle-on' => array( 'group' => 'solid' ),
					'fas fa-trademark' => array( 'group' => 'solid' ),
					'fas fa-train' => array( 'group' => 'solid' ),
					'fas fa-transgender' => array( 'group' => 'solid' ),
					'fas fa-transgender-alt' => array( 'group' => 'solid' ),
					'fas fa-trash' => array( 'group' => 'solid' ),
					'fas fa-trash-alt' => array( 'group' => 'solid' ),
					'fas fa-tree' => array( 'group' => 'solid' ),
					'fas fa-trophy' => array( 'group' => 'solid' ),
					'fas fa-truck' => array( 'group' => 'solid' ),
					'fas fa-truck-loading' => array( 'group' => 'solid' ),
					'fas fa-truck-moving' => array( 'group' => 'solid' ),
					'fas fa-tty' => array( 'group' => 'solid' ),
					'fas fa-tv' => array( 'group' => 'solid' ),
					'fas fa-umbrella' => array( 'group' => 'solid' ),
					'fas fa-underline' => array( 'group' => 'solid' ),
					'fas fa-undo' => array( 'group' => 'solid' ),
					'fas fa-undo-alt' => array( 'group' => 'solid' ),
					'fas fa-universal-access' => array( 'group' => 'solid' ),
					'fas fa-university' => array( 'group' => 'solid' ),
					'fas fa-unlink' => array( 'group' => 'solid' ),
					'fas fa-unlock' => array( 'group' => 'solid' ),
					'fas fa-unlock-alt' => array( 'group' => 'solid' ),
					'fas fa-upload' => array( 'group' => 'solid' ),
					'fas fa-user' => array( 'group' => 'solid' ),
					'fas fa-user-circle' => array( 'group' => 'solid' ),
					'fas fa-user-md' => array( 'group' => 'solid' ),
					'fas fa-user-plus' => array( 'group' => 'solid' ),
					'fas fa-user-secret' => array( 'group' => 'solid' ),
					'fas fa-user-times' => array( 'group' => 'solid' ),
					'fas fa-users' => array( 'group' => 'solid' ),
					'fas fa-utensil-spoon' => array( 'group' => 'solid' ),
					'fas fa-utensils' => array( 'group' => 'solid' ),
					'fas fa-venus' => array( 'group' => 'solid' ),
					'fas fa-venus-double' => array( 'group' => 'solid' ),
					'fas fa-venus-mars' => array( 'group' => 'solid' ),
					'fas fa-vial' => array( 'group' => 'solid' ),
					'fas fa-vials' => array( 'group' => 'solid' ),
					'fas fa-video' => array( 'group' => 'solid' ),
					'fas fa-video-slash' => array( 'group' => 'solid' ),
					'fas fa-volleyball-ball' => array( 'group' => 'solid' ),
					'fas fa-volume-down' => array( 'group' => 'solid' ),
					'fas fa-volume-off' => array( 'group' => 'solid' ),
					'fas fa-volume-up' => array( 'group' => 'solid' ),
					'fas fa-warehouse' => array( 'group' => 'solid' ),
					'fas fa-weight' => array( 'group' => 'solid' ),
					'fas fa-wheelchair' => array( 'group' => 'solid' ),
					'fas fa-wifi' => array( 'group' => 'solid' ),
					'fas fa-window-close' => array( 'group' => 'solid' ),
					'fas fa-window-maximize' => array( 'group' => 'solid' ),
					'fas fa-window-minimize' => array( 'group' => 'solid' ),
					'fas fa-window-restore' => array( 'group' => 'solid' ),
					'fas fa-wine-glass' => array( 'group' => 'solid' ),
					'fas fa-won-sign' => array( 'group' => 'solid' ),
					'fas fa-wrench' => array( 'group' => 'solid' ),
					'fas fa-x-ray' => array( 'group' => 'solid' ),
					'fas fa-yen-sign' => array( 'group' => 'solid' ),
					'far fa-address-book' => array( 'group' => 'regular' ),
					'far fa-address-card' => array( 'group' => 'regular' ),
					'far fa-arrow-alt-circle-down' => array( 'group' => 'regular' ),
					'far fa-arrow-alt-circle-left' => array( 'group' => 'regular' ),
					'far fa-arrow-alt-circle-right' => array( 'group' => 'regular' ),
					'far fa-arrow-alt-circle-up' => array( 'group' => 'regular' ),
					'far fa-bell' => array( 'group' => 'regular' ),
					'far fa-bell-slash' => array( 'group' => 'regular' ),
					'far fa-bookmark' => array( 'group' => 'regular' ),
					'far fa-building' => array( 'group' => 'regular' ),
					'far fa-calendar' => array( 'group' => 'regular' ),
					'far fa-calendar-alt' => array( 'group' => 'regular' ),
					'far fa-calendar-check' => array( 'group' => 'regular' ),
					'far fa-calendar-minus' => array( 'group' => 'regular' ),
					'far fa-calendar-plus' => array( 'group' => 'regular' ),
					'far fa-calendar-times' => array( 'group' => 'regular' ),
					'far fa-caret-square-down' => array( 'group' => 'regular' ),
					'far fa-caret-square-left' => array( 'group' => 'regular' ),
					'far fa-caret-square-right' => array( 'group' => 'regular' ),
					'far fa-caret-square-up' => array( 'group' => 'regular' ),
					'far fa-chart-bar' => array( 'group' => 'regular' ),
					'far fa-check-circle' => array( 'group' => 'regular' ),
					'far fa-check-square' => array( 'group' => 'regular' ),
					'far fa-circle' => array( 'group' => 'regular' ),
					'far fa-clipboard' => array( 'group' => 'regular' ),
					'far fa-clock' => array( 'group' => 'regular' ),
					'far fa-clone' => array( 'group' => 'regular' ),
					'far fa-closed-captioning' => array( 'group' => 'regular' ),
					'far fa-comment' => array( 'group' => 'regular' ),
					'far fa-comment-alt' => array( 'group' => 'regular' ),
					'far fa-comments' => array( 'group' => 'regular' ),
					'far fa-compass' => array( 'group' => 'regular' ),
					'far fa-copy' => array( 'group' => 'regular' ),
					'far fa-copyright' => array( 'group' => 'regular' ),
					'far fa-credit-card' => array( 'group' => 'regular' ),
					'far fa-dot-circle' => array( 'group' => 'regular' ),
					'far fa-edit' => array( 'group' => 'regular' ),
					'far fa-envelope' => array( 'group' => 'regular' ),
					'far fa-envelope-open' => array( 'group' => 'regular' ),
					'far fa-eye-slash' => array( 'group' => 'regular' ),
					'far fa-file' => array( 'group' => 'regular' ),
					'far fa-file-alt' => array( 'group' => 'regular' ),
					'far fa-file-archive' => array( 'group' => 'regular' ),
					'far fa-file-audio' => array( 'group' => 'regular' ),
					'far fa-file-code' => array( 'group' => 'regular' ),
					'far fa-file-excel' => array( 'group' => 'regular' ),
					'far fa-file-image' => array( 'group' => 'regular' ),
					'far fa-file-pdf' => array( 'group' => 'regular' ),
					'far fa-file-powerpoint' => array( 'group' => 'regular' ),
					'far fa-file-video' => array( 'group' => 'regular' ),
					'far fa-file-word' => array( 'group' => 'regular' ),
					'far fa-flag' => array( 'group' => 'regular' ),
					'far fa-folder' => array( 'group' => 'regular' ),
					'far fa-folder-open' => array( 'group' => 'regular' ),
					'far fa-frown' => array( 'group' => 'regular' ),
					'far fa-futbol' => array( 'group' => 'regular' ),
					'far fa-gem' => array( 'group' => 'regular' ),
					'far fa-hand-lizard' => array( 'group' => 'regular' ),
					'far fa-hand-paper' => array( 'group' => 'regular' ),
					'far fa-hand-peace' => array( 'group' => 'regular' ),
					'far fa-hand-point-down' => array( 'group' => 'regular' ),
					'far fa-hand-point-left' => array( 'group' => 'regular' ),
					'far fa-hand-point-right' => array( 'group' => 'regular' ),
					'far fa-hand-point-up' => array( 'group' => 'regular' ),
					'far fa-hand-pointer' => array( 'group' => 'regular' ),
					'far fa-hand-rock' => array( 'group' => 'regular' ),
					'far fa-hand-scissors' => array( 'group' => 'regular' ),
					'far fa-hand-spock' => array( 'group' => 'regular' ),
					'far fa-handshake' => array( 'group' => 'regular' ),
					'far fa-hdd' => array( 'group' => 'regular' ),
					'far fa-heart' => array( 'group' => 'regular' ),
					'far fa-hospital' => array( 'group' => 'regular' ),
					'far fa-hourglass' => array( 'group' => 'regular' ),
					'far fa-id-badge' => array( 'group' => 'regular' ),
					'far fa-id-card' => array( 'group' => 'regular' ),
					'far fa-image' => array( 'group' => 'regular' ),
					'far fa-images' => array( 'group' => 'regular' ),
					'far fa-keyboard' => array( 'group' => 'regular' ),
					'far fa-lemon' => array( 'group' => 'regular' ),
					'far fa-life-ring' => array( 'group' => 'regular' ),
					'far fa-lightbulb' => array( 'group' => 'regular' ),
					'far fa-list-alt' => array( 'group' => 'regular' ),
					'far fa-map' => array( 'group' => 'regular' ),
					'far fa-meh' => array( 'group' => 'regular' ),
					'far fa-minus-square' => array( 'group' => 'regular' ),
					'far fa-money-bill-alt' => array( 'group' => 'regular' ),
					'far fa-moon' => array( 'group' => 'regular' ),
					'far fa-newspaper' => array( 'group' => 'regular' ),
					'far fa-object-group' => array( 'group' => 'regular' ),
					'far fa-object-ungroup' => array( 'group' => 'regular' ),
					'far fa-paper-plane' => array( 'group' => 'regular' ),
					'far fa-pause-circle' => array( 'group' => 'regular' ),
					'far fa-play-circle' => array( 'group' => 'regular' ),
					'far fa-plus-square' => array( 'group' => 'regular' ),
					'far fa-question-circle' => array( 'group' => 'regular' ),
					'far fa-registered' => array( 'group' => 'regular' ),
					'far fa-save' => array( 'group' => 'regular' ),
					'far fa-share-square' => array( 'group' => 'regular' ),
					'far fa-smile' => array( 'group' => 'regular' ),
					'far fa-snowflake' => array( 'group' => 'regular' ),
					'far fa-square' => array( 'group' => 'regular' ),
					'far fa-star' => array( 'group' => 'regular' ),
					'far fa-star-half' => array( 'group' => 'regular' ),
					'far fa-sticky-note' => array( 'group' => 'regular' ),
					'far fa-stop-circle' => array( 'group' => 'regular' ),
					'far fa-sun' => array( 'group' => 'regular' ),
					'far fa-thumbs-down' => array( 'group' => 'regular' ),
					'far fa-thumbs-up' => array( 'group' => 'regular' ),
					'far fa-times-circle' => array( 'group' => 'regular' ),
					'far fa-trash-alt' => array( 'group' => 'regular' ),
					'far fa-user' => array( 'group' => 'regular' ),
					'far fa-user-circle' => array( 'group' => 'regular' ),
					'far fa-window-close' => array( 'group' => 'regular' ),
					'far fa-window-maximize' => array( 'group' => 'regular' ),
					'far fa-window-minimize' => array( 'group' => 'regular' ),
					'far fa-window-restore' => array( 'group' => 'regular' ),
				),
			),
		);
	}

}

DMS_Option_Type::register( 'DMS_Option_Type_NewIcon' );
